Numpy

In [12]:
#1.Create a 1D array from a list.
import numpy as np
cr = np.array((12,23,44))
print(cr)

[12 23 44]


In [16]:
#2. Create a 3x3 array of zeros.
import numpy as np
cr = np.zeros((3,3))
print(cr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# 3. Create a 2x2 array of ones.
import numpy as np
cr = np.ones((2,2))
print(cr)

[[1. 1.]
 [1. 1.]]


In [20]:
#4. Generate array from 0 to 10 (exclusive).
import numpy as np
cr = np.arange(0,11,1)
print(cr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [22]:
#5. Create 5 evenly spaced numbers between 0 and 1.
import numpy as np
cr = np.linspace(0,1,5)
print(cr)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
#6. Create a 4x4 identity matrix.
import numpy as np
cr = np.eye(4)
print(cr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
#7. Reshape 1D array to 2D.
import numpy as np
cr = np.array((12,23,44,56))
cr.resize((2,2))
print(cr)

[[12 23]
 [44 56]]


In [77]:
#8. Get the shape and dtype of an array.
import numpy as np
cr = np.array((12,23,44,56))
print(cr.shape ,"\n\n",cr.dtype)

(4,) 

 int64


In [30]:
#9. Reverse a NumPy array.
import numpy as np
cr = np.array((12,23,34,45))
print(cr[::-1])

[45 34 23 12]


In [32]:
#10. Extract even numbers from an array.
import numpy as np
cr = np.array((12,23,34,45))
for i in cr:
    if i%2 == 0:
        print(i,end=" ")

12 34 

In [41]:
# 11. Find the max in each row.
import numpy as np
cr = np.array([(12,23,45),
               (34,45,77),
               (88,76,44)])
x,y,z = np.split(cr,3)
print(x.max () , " " , y.max(), " " , z.max())

45   77   88


In [48]:
#12. Compute the mean, std, and median of an array.
import numpy as np
cr = np.array((12,23,6,34,45))
print("Mean is " , cr.mean(), "\nStandard Deviation is ",cr.std(),"\nMedian is ",np.median(cr))

Mean is  24.0 
Standard Deviation is  14.212670403551895 
Median is  23.0


In [50]:
# 13. Stack two arrays vertically.
import numpy as np
cr = np.array((12,23,34))
cr1 = np.array((45,56,78))
vertical_stack = np.vstack((cr,cr1))
print(vertical_stack)

[[12 23 34]
 [45 56 78]]


In [51]:
# 14. Stack two arrays horizontally.
import numpy as np
cr = np.array((12,23,34))
cr1 = np.array((45,56,78))
horizontal_stack = np.hstack((cr,cr1))
print(horizontal_stack)

[12 23 34 45 56 78]


In [52]:
# 15. Stack two arrays horizontally.
import numpy as np
cr = np.array((12,23,34))
cr1 = np.array((45,56,78))
horizontal_stack = np.hstack((cr,cr1))
print(horizontal_stack)

[12 23 34 45 56 78]


In [ ]:
#16. Find the unique values and their counts.
import numpy as np
cr = np.array((12,12,22,33,44,55,55,55))
values , counts = np.unique(cr,return_counts=True)
print("Values are ",values , "and their Counts are ",counts)

Values are  [12 22 33 44 55] and their Counts are  [2 1 1 1 3]


In [1]:
#17.Replace NaN with column means.
import numpy as np
data = np.array([[1, 2, np.nan],
                 [4, np.nan, 6],
                 [7, 8, 9]])
col_means = np.nanmean(data, axis=0)
inds = np.where(np.isnan(data))
data[inds] = np.take(col_means, inds[1])
print(data)



[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [4]:
#18. Get index of min and max values.
import numpy as np
cr = np.array([(2,3,1),
               (4,5,6),
               (7,9,8)])
max , min = cr.max() , cr.min()
print("Max value is " , max , " and min value is ",min)
max_args , min_args = cr.argmax() , cr.argmin()
print("Index of max value is " , max_args," and min value is " , min_args)

Max value is  9  and min value is  1
Index of max value is  7  and min value is  2


In [10]:
#19.Create a 3D array of random integers.
import numpy as np
array_3d = np.random.randint(0, 10, size=(2, 3, 4))
print(array_3d)

[[[3 4 8 6]
  [6 5 3 3]
  [8 7 8 9]]

 [[2 2 7 5]
  [7 5 9 9]
  [7 0 2 1]]]


In [12]:
#20. Use np.where() to replace values
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = np.where(arr % 2 == 0, 'even', 'odd')
print(x)


['odd' 'even' 'odd' 'even' 'odd']


Pandas 

In [13]:
#1. Create a Series using a Python list.
import pandas as pd
x = pd.Series([12,23,34])
print(x)

0    12
1    23
2    34
dtype: int64


In [16]:
#2. Create a Series with custom string indices.
import pandas as pd
x = pd.Series(["Apple","Banana","Chiku"],index=['One','Two','Three'])
print(x)

One       Apple
Two      Banana
Three     Chiku
dtype: object


In [19]:
#3. Create a Series from a dictionary.
import pandas as pd
x = pd.Series({"Math":["Trigonometry","Calculus"],"Chemistry":["Organic","Inorganic"]})
print(x)

Math         [Trigonometry, Calculus]
Chemistry        [Organic, Inorganic]
dtype: object


In [24]:
#4. Access first 3 elements of a Series.
import pandas as pd
x = pd.Series([44,55,66,77,88,99])
print(x[0:3])

0    44
1    55
2    66
dtype: int64


In [27]:
#5. Filter Series elements greater than 50.
import pandas as pd
x = pd.Series([11,22,33,66,77,88,99])
print(x[x>50])

3    66
4    77
5    88
6    99
dtype: int64


In [34]:
#6. Add two Series with different indices.
import pandas as pd
x = pd.Series([1, 2, 3, 4, 5], index=[0, 1, 2, 3, 4])
y = pd.Series([6, 7, 8, 9, 10], index=[2, 3, 4, 5, 6])
result = x.add(y, fill_value=0)
print(result)


0     1.0
1     2.0
2     9.0
3    11.0
4    13.0
5     9.0
6    10.0
dtype: float64


In [35]:
#7. Multiply a Series by a scalar.
import pandas as pd
x = pd.Series([11,22,33,44,55])
print(x*2)

0     22
1     44
2     66
3     88
4    110
dtype: int64


In [36]:
#8. Use .multiply() method to multiply with scalar.
import pandas as pd
x = pd.Series([11,22,33,44,55])
print(x.multiply(3))

0     33
1     66
2     99
3    132
4    165
dtype: int64


In [42]:
#10. Sort Series by values descending.
import pandas as pd
x = pd.Series([11,22,21,44,55])
print(x.sort_values(ascending=False))

4    55
3    44
1    22
2    21
0    11
dtype: int64


In [43]:
#11. Sort Series by index.
import pandas as pd
x = pd.Series([11, 22, 33, 44, 55], index=[3, 1, 4, 0, 2])
print(x.sort_index())

0    44
1    22
2    55
3    11
4    33
dtype: int64


In [47]:
#12. Check for null values.
import pandas as pd
import numpy as np
x = pd.Series([12,np.nan,67,88,np.nan])
print(x.isna())

0    False
1     True
2    False
3    False
4     True
dtype: bool


In [51]:
#14. Concatenate two Series using concat().
import pandas as pd
x = pd.Series([1,2,3,4,5])
y = pd.Series([6,7,8,9,10])
print(pd.concat([x,y]))

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64


In [56]:
#15. Concatenate two Series using append().
import pandas as pd
x = pd.Series([1,2,3,4,5])
y = pd.Series([6,7,8,9,10])
# print(x.append(y))

In [57]:
#16. Retrieve first 5 elements using .head()
import pandas as pd
x = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(x.head())

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [58]:
#17. Retrieve last 5 elements using .tail()
import pandas as pd
x = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(x.tail())

5     6
6     7
7     8
8     9
9    10
dtype: int64


In [64]:
#18. Convert Series to DataFrame.
import pandas as pd
x = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(pd.DataFrame(x,columns=["Numbers"]))

   Numbers
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10


In [ ]:
# 19. Replace NaN with 0.
import numpy as np
import pandas as pd
x = pd.Series([12,np.nan,67,88,np.nan])
print(x.replace(np.nan,0))

0    12.0
1     0.0
2    67.0
3    88.0
4     0.0
dtype: float64


In [73]:
#20. Drop missing values.
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [np.nan, 6, 7, 8]
})
print(df.dropna())

     A    B
1  2.0  6.0
3  4.0  8.0


In [75]:
#21. Check Series data type.
import pandas as pd
x = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(x.dtype)

int64
